name: image-push

on:
  push:
    branches:
      - main
      - stable
      - arm-support
    tags:
      - '[0-9]+.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag to nightly
        if: endsWith(github.ref, '/main')
        run: echo "TAG=nightly" >> $GITHUB_ENV
      -
        name: Set tag to stable or latest
        if: endsWith(github.ref, '/stable')
        run: echo "TAG=latest" >> $GITHUB_ENV
      -
        name: Set tag to git tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push PDK
        id: docker_build_pdk
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
             odidev/pdk:latest
      -
        name: Image digest
        run: |
          echo 'PDK: ${{ steps.docker_build_pdk.outputs.digest }}'
